<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="_Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <style>
        body {
    background-image: url('green.png');
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    font-family: Arial, sans-serif;
    margin: 10px;
    padding: 10px;
}
         body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            margin: 0;
            padding: 0;
        }

        /* Container styles */
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }

        /* Jumbotron styles */
        .jumbotron {
            background-color: #007bff;
            color: #fff;
            padding: 50px;
            text-align: center;
            border-radius: 10px;
        }
        .blurred-background {
            background-image: url('green,png'); /* Specify your background image */
            background-size: cover; /* Ensure the background image covers the entire element */
            backdrop-filter: blur(10px); /* Apply a blur effect to the background */
            -webkit-backdrop-filter: blur(10px); /* For Safari */
            padding: 50px;
            text-align: center;
            border-radius: 10px;
        }


        .jumbotron h1 {
            font-size: 36px;
            margin-bottom: 20px;
        }

        .jumbotron p {
            font-size: 18px;
            line-height: 1.6;
            margin-bottom: 20px;
        }

        .jumbotron .btn {
            font-size: 20px;
            padding: 10px 20px;
            border-radius: 5px;
            background-color: #fff;
            color: #007bff;
            text-decoration: none;
        }

        .jumbotron .btn:hover {
            background-color: #e6e6e6;
        }

        /* Row styles */
        .row {
            display: flex;
            justify-content: space-between;
            margin-top: 30px;
        }

        /* Column styles */
        .col-md-4 {
            width: 50%;
            margin: 50px auto; /* Center the container vertically and horizontally */
            padding: 20px;
            background-color: rgba(255, 255, 255, 0.3); /* Transparent white background */
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
        }

        .col-md-4 h2 {
            font-size: 24px;
            margin-bottom: 15px;
        }

        .col-md-4 p {
            font-size: 16px;
            line-height: 1.6;
            margin-bottom: 20px;
        }

        .col-md-4 .btn {
            font-size: 16px;
            padding: 8px 16px;
            border-radius: 5px;
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
        }

        .col-md-4 .btn:hover {
            background-color: #0056b3;
        }
    </style>

    <div class="blurred-background">
       <img src="EIA.png" alt="EIA Logo" class="eia-logo">
        <p> </p>
        <p class="lead"></p>
        <p><a href="/Account/Login" class="btn btn-primary btn-lg">GET STARTED &raquo;</a></p>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h2>WHAT IS ECO IMPACT AFRICA</h2>
            <p>
                is a startup organization with a strong commitment to environmental sustainability.  
                We are a renewable energy company committed to accelerating the global transition to a sustainable, 
                low carbon future. We offer a wide range of innovative and customized clean energy solutions designed to
                meet the unique needs of individuals and businesses. We are particularly interested in the 
                implementation of these technologies in Africa, a continent with immense potential for renewable energy development.
            </p>
        </div>
        <div class="col-md-4">
            <img src="cop.png" width="300"/>
        </div>
        <div class="col-md-4">
            <h2>CARBON FOOTPRINT CALCULATOR</h2>
            <p>
                A Carbon Footprint Calculator is a tool designed to estimate the amount of 
                greenhouse gas emissions generated by an individual, household, organization,
                product, or event over a specified period.
            </p>
            <p>
                <a class="btn btn-default" href="calculator">calculate &raquo;</a>
            </p>
        </div>
    </div>
</asp:Content>
